{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "0169dd0c-751d-4932-b0a8-c6875d16b312",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 70, in <module>\n",
      "    min_height = min(contactheight)\n",
      "ValueError: min() arg is an empty sequence\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 169, in <module>\n",
      "    wafer_map.save(out_path, dpi=300)\n",
      "TypeError: save() got an unexpected keyword argument 'dpi'\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 27, in <module>\n",
      "    log_content = file.readlines()\n",
      "  File \"/usr/lib64/python3.9/codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 27, in <module>\n",
      "    log_content = file.readlines()\n",
      "  File \"/usr/lib64/python3.9/codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 169, in <module>\n",
      "    wafer_map.save(out_path, dpi=300)\n",
      "TypeError: save() got an unexpected keyword argument 'dpi'\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 27, in <module>\n",
      "    log_content = file.readlines()\n",
      "  File \"/usr/lib64/python3.9/codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 27, in <module>\n",
      "    log_content = file.readlines()\n",
      "  File \"/usr/lib64/python3.9/codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 27, in <module>\n",
      "    log_content = file.readlines()\n",
      "  File \"/usr/lib64/python3.9/codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 169, in <module>\n",
      "    wafer_map.save(out_path, dpi=300)\n",
      "TypeError: save() got an unexpected keyword argument 'dpi'\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 27, in <module>\n",
      "    log_content = file.readlines()\n",
      "  File \"/usr/lib64/python3.9/codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 169, in <module>\n",
      "    wafer_map.save(out_path, dpi=300)\n",
      "TypeError: save() got an unexpected keyword argument 'dpi'\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 27, in <module>\n",
      "    log_content = file.readlines()\n",
      "  File \"/usr/lib64/python3.9/codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 169, in <module>\n",
      "    wafer_map.save(out_path)\n",
      "TypeError: save() got an unexpected keyword argument 'dpi'\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 27, in <module>\n",
      "    log_content = file.readlines()\n",
      "  File \"/usr/lib64/python3.9/codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 27, in <module>\n",
      "    log_content = file.readlines()\n",
      "  File \"/usr/lib64/python3.9/codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte\n",
      "\n",
      "Error running script: Traceback (most recent call last):\n",
      "  File \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\", line 27, in <module>\n",
      "    log_content = file.readlines()\n",
      "  File \"/usr/lib64/python3.9/codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import subprocess\n",
    "import os\n",
    "\n",
    "root_path = os.path.expanduser(\"~/Desktop/log_files/\")\n",
    "for root, dirs, files in os.walk(root_path):\n",
    "    for file_name in files:\n",
    "        file_path = os.path.join(root, file_name)\n",
    "\n",
    "        # Command to execute your Python script (replace with your script path and any arguments)\n",
    "        script_path = \"/nfshome/natpenn/Desktop/CMS-Wafer-Testing/Topography-Maps/topography_map.py\"\n",
    "        command = ['python3.9', script_path, file_path]\n",
    "\n",
    "        # Run the script as a subprocess\n",
    "        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)\n",
    "\n",
    "        # Wait for the process to complete and capture output (optional)\n",
    "        stdout, stderr = process.communicate()\n",
    "\n",
    "        # Check if there was an error\n",
    "        if process.returncode != 0:\n",
    "            print(f\"Error running script: {stderr.decode('utf-8')}\")\n",
    "        else:\n",
    "            print(f\"Script ran successfully: {stdout.decode('utf-8')}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0d00fa48-bd13-4110-a397-93ff5a5b0736",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
